root: true
env:
  browser: true
  es2021: true
  node: true
parser: vue-eslint-parser
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - plugin:prettier/recommended
  - './.eslintrc-auto-import.json'
overrides: [ ]
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - vue
  - prettier
rules:
  prettier/prettier: error
