root: true
env:
  browser: true
  es2021: true
  node: true
parser: vue-eslint-parser
extends:
  - eslint:recommended
  - plugin:vue/vue3-recommended
  - prettier
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
plugins:
  - vue
rules: {}
