root: true
env:
  browser: true
  es2021: true
  node: true
extends:
  - plugin:vue/vue3-recommended
  - standard
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
  ecmaFeatures:
    jsx: true
    modules: true
  parser: '@babel/eslint-parser'
plugins:
  - vue
  - prettier
rules: {}
